language: node_js
node_js:
  - 11.6.0

cache: npm

install:
  - npm ci

script:
  - npm test
  - npm build || true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $ GITHUB_TOKEN
  on:
    branch: gh-pages
