version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.18.1
    working_directory: ~/my-app/my-app

    steps:
      - checkout:
          path: ~/my-app
      - run:
          name: Update NPM
          command: ls 
      - restore_cache:
          
          keys: 
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-          
      - run: cd my-app && npm install
      - save_cache:
          paths:
            - ./node_modules
          
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          
workflows:
  version: 2
  build-deploy:
    jobs:
      - build