version: 2.1

jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: cimg/node:14.18.1
    steps:
      - checkout
      - run:
          name: Update NPM
          command: ls my-app/
      - restore_cache:
          paths:
            - ./node_modules/cache
          key: dependency-cache-{{ checksum "my-app/package.json" }}
          
      # - run:
      #     name: Install Dependencies
      #     command: cd my-app && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "my-app/package.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  build-deploy:
    jobs:
      - build