version: 2.1
# jobs is the task which are working for

jobs:
  test:
    docker:
      - image: circleci/node:14.18.1
    # for working_directory give your app name
    working_directory: ~/my-app/

    steps:
      - checkout

      - restore_cache:
           name: Restore Yarn Package Cache
           keys:
             - m2-npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Install dependencies
          command: npm install
       - save_cache:
           name: Save Yarn Package Cache
           key: m2-npm-packages-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
           paths:
             - ./node_modules/

      # - run:
      #     name: install dependencies
      #     command: cd my-app && npm install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v2-dependencies-{{checksum "my-app/package.json"}}
      # - run:
      #     name: run test
      #     command: cd my-app && npm run test

workflows:
  test-depoly:
    jobs:
      - test
      # - two
