version: 2.1
jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "my-app/package.json" }}
      - run:
          name: Install Dependencies
          command: cd my-app && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "my-app/package.json" }}
          paths:
            - cd my-ap && ./node_modules
workflows:
  version: 2
  build-deploy:
    jobs:
      - build