version: 2.1
# jobs is the task which are working for

jobs:
  test:
    docker:
      - image: cimg/node:18.7.0
    # for working_directory give your app name
    working_directory: ~/my-app/

    steps:
      - checkout

      - run:
          name: lsist
          command: ls my-app/

      - run:
          name: pwd
          command: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "my-app/package.json"}}

      - run:
          name: install dependencies
          command: cd my-app && npm install

      - save_cache:
          paths:
            - node_modules
            - package.json
          key: v1-dependencies-{{checksum "my-app/package.json"}}
      - run:
          name: run test
          command: cd my-app && npm run test

workflows:
  test-depoly:
    jobs:
      - test
      # - two
