version: 2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:14.18.1

    working_directory: ~/my-app

    steps:
      - checkout

      - restore_cache:
        key: v1-deps-{{checksum "my-app/package.json"}}

      - run:
        name: install dependencies
        command: npm install

      - save_cache:
        key: v1-deps-{{ checksum "my-app/package.json"}}
        path:
          - node_modules

      # - run: cd my-app && npm run test
      - run: cd my-app && npm run build
