version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.18.1
    working_directory: ~/my-app

    steps:
      - checkout
      - run:
          name: Update NPM
          command: ls my-app/
      - restore_cache:
          
          key: dependencies-cache-{{ checksum "my-app/package-lock.json" }}
          
      # - run:
      #     name: Install Dependencies
      #     command: cd my-app && npm install
      - save_cache:
          key: dependencies-cache-{{ checksum "my-app/package-lock.json" }}
          paths:
            - ./node_modules/cache
workflows:
  version: 2
  build-deploy:
    jobs:
      - build