version: 2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:11.10.1

    steps:
      - checkout

      - restore_cache:
        key: v1-deps-{{checksum "package-lock.json"}}

      - run:
        name: install dependencies
        command: npm install

      - save_cache:
        key: v1-deps-{{ checksum "package_lock.json"}}
        path:
          - node_modules

      - run: npm test
      - run: npm build
